// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mllyovnjqxhppqvdphqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sbHlvdm5qcXhocHBxdmRwaHF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NjczMjksImV4cCI6MjA2MjE0MzMyOX0.hHBZ2LMpZFOg-N6lM3aYFdT9pyEwhtcu4dClAgiegMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);